#
#Thanks for downloading my temporary fix for CrazyEnchantments Duplication Bug!
#
# If you configure this make sure
# '' <-- that this shouldn't be remove when you change the name.
# 

Name: '&a&lBlack Scroll'